# Generated by Django 6.0.3 on 2026-04-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100)),
                ('resource_group', models.CharField(max_length=200)),
                ('service_type', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('cost_amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=100)),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('env', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_resource_id', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
