# Generated by Django 6.0.3 on 2026-04-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_organization_costrecord_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorganization',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10),
        ),
    ]
